[project]
name = "flight-delay-rotation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shu Chen", email = "chenshu@unc.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "airportsdata>=20260905",
    "duckdb>=1.5.5",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
]

[project.scripts]
flight-delay-rotation = "flight_delay_rotation:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
